repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        name: ruff-fix-imports
        args: ["--fix", "--select", "I"]

      - id: ruff-format
        name: ruff-format

      - id: ruff
        name: ruff-lint
        args: ["--ignore", "I"]
