AWSTemplateFormatVersion: 2010-09-09
Description: This template creates an EKS cluster with an EC2 node group.

Parameters:
  EKSClusterName:
    Description: Name of the EKS Cluster
    Type: String
    Default: aws-deployments-eks-ec2

  EKSClusterRoleName:
    Description: Name of the EKS Cluster Role
    Type: String
    Default: EKSClusterRole-aws-eks-ec2

  EKSNodeInstanceRoleName:
    Description: Name of the EKS Node Instance Role
    Type: String
    Default: EKSNodeInstanceRole-aws-eks-ec2

  VPCStackName:
    Description: Name of the VPC CloudFormation stack to import subnet IDs from
    Type: String
    Default: eks-vpc-stack

Resources:
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref EKSClusterRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  EKSNodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref EKSNodeInstanceRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref EKSClusterName
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds:
          Fn::Split:
            - ","
            - Fn::ImportValue: !Sub "${VPCStackName}-AllSubnets"
        EndpointPublicAccess: true
        EndpointPrivateAccess: true
      Version: "1.33"

  EKSNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      AmiType: AL2023_x86_64_STANDARD
      CapacityType: SPOT
      ClusterName: !Ref EKSCluster
      DiskSize: 20
      NodeRole: !GetAtt EKSNodeInstanceRole.Arn
      Subnets:
        Fn::Split:
          - ","
          - Fn::ImportValue: !Sub "${VPCStackName}-PrivateSubnets"
      ScalingConfig:
        DesiredSize: 2
        MinSize: 2
        MaxSize: 4
      InstanceTypes:
        - t3.medium
      NodegroupName: !Sub "${EKSClusterName}-nodegroup"


Outputs:
  ClusterName:
    Description: Name of EKS Cluster
    Value: !Ref EKSCluster
