AWSTemplateFormatVersion: 2010-09-09
Description: This template creates an EKS cluster with Fargate profiles and IAM configurations for the ALB Controller.

Parameters:
  EKSClusterName:
    Description: Name of the EKS Cluster
    Type: String
    Default: aws-deployments-eks-fargate

  EKSClusterRoleName:
    Description: Name of the EKS Cluster Role
    Type: String
    Default: EKSClusterRole-aws-eks-fargate

  FargatePodExecutionRoleName:
    Description: Name of the EKS Fargate Pod Execution Role
    Type: String
    Default: FargatePodExecutionRole-aws-eks-fargate

  EKSClusterSubnets:
    Description: Comma-separated list of VPC Subnet IDs for the EKS Cluster (must be private subnets with a NAT Gateway for Fargate)
    Type: CommaDelimitedList
    Default: subnet-0ef08e10d6000f307,subnet-0a960f1032e9dc58e,subnet-0009006416de50ea2

Resources:
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref EKSClusterRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  FargatePodExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref FargatePodExecutionRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks-fargate-pods.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSFargatePodExecutionRolePolicy

  EKSCluster:
    Type: AWS::EKS::Cluster
    DependsOn:
      - EKSClusterRole
    Properties:
      Name: !Ref EKSClusterName
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds: !Ref EKSClusterSubnets
      Version: "1.34"

  EKSFargateProfileDefault:
    Type: AWS::EKS::FargateProfile
    DependsOn:
      - EKSCluster
      - FargatePodExecutionRole
    Properties:
      ClusterName: !Ref EKSCluster
      FargateProfileName: !Sub "${EKSClusterName}-fargate-profile-default"
      PodExecutionRoleArn: !GetAtt FargatePodExecutionRole.Arn
      Subnets: !Ref EKSClusterSubnets
      Selectors:
        - Namespace: default

  EKSFargateProfileKubeSystem:
    Type: AWS::EKS::FargateProfile
    DependsOn:
      - EKSCluster
      - FargatePodExecutionRole
    Properties:
      ClusterName: !Ref EKSCluster
      FargateProfileName: !Sub "${EKSClusterName}-fargate-profile-kubesystem"
      PodExecutionRoleArn: !GetAtt FargatePodExecutionRole.Arn
      Subnets: !Ref EKSClusterSubnets
      Selectors:
        - Namespace: kube-system

  OIDCProvider:
    Type: AWS::IAM::OIDCProvider
    DependsOn: EKSCluster
    Properties:
      Url: !GetAtt EKSCluster.OpenIdConnectIssuerUrl
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 9e259524a39199a65606278749117d3b55a18640

  ALBControllerRole:
    Type: AWS::IAM::Role
    DependsOn: OIDCProvider
    Properties:
      RoleName: !Sub "${EKSClusterName}-alb-controller-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref OIDCProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                !Sub
                  - "${Issuer}:aud"
                  - Issuer: !GetAtt EKSCluster.OpenIdConnectIssuerUrl
                !Sub
                  - "${Issuer}:sub"
                  - Issuer: !GetAtt EKSCluster.OpenIdConnectIssuerUrl
                "system:serviceaccount:kube-system:aws-load-balancer-controller"
      Policies:
        - PolicyName: EKSALBControllerPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iam:CreateServiceLinkedRole
                  - ec2:DescribeAccountAttributes
                  - ec2:DescribeAddresses
                  - ec2:DescribeAvailabilityZones
                  - ec2:DescribeInternetGateways
                  - ec2:DescribeVpcs
                  - ec2:DescribeSubnets
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeInstances
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DescribeTags
                  - ec2:GetCoipPoolDetails
                  - ec2:DescribeCoipPools
                  - elasticloadbalancing:DescribeLoadBalancers
                  - elasticloadbalancing:DescribeLoadBalancerAttributes
                  - elasticloadbalancing:DescribeListeners
                  - elasticloadbalancing:DescribeListenerCertificates
                  - elasticloadbalancing:DescribeSSLPolicies
                  - elasticloadbalancing:DescribeRules
                  - elasticloadbalancing:DescribeTargetGroups
                  - elasticloadbalancing:DescribeTargetGroupAttributes
                  - elasticloadbalancing:DescribeTargetHealth
                  - elasticloadbalancing:DescribeTrustStores
                Resource: "*"
              - Effect: Allow
                Action:
                  - cognito-idp:DescribeUserPoolClient
                  - acm:ListCertificates
                  - acm:DescribeCertificate
                  - iam:ListServerCertificates
                  - iam:GetServerCertificate
                  - waf-regional:GetWebACL
                  - waf-regional:GetWebACLForResource
                  - waf-regional:AssociateWebACL
                  - waf-regional:DisassociateWebACL
                  - wafv2:GetWebACL
                  - wafv2:GetWebACLForResource
                  - wafv2:AssociateWebACL
                  - wafv2:DisassociateWebACL
                  - shield:GetSubscriptionState
                  - shield:DescribeProtection
                  - shield:CreateProtection
                  - shield:DeleteProtection
                Resource: "*"
              - Effect: Allow
                Action:
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:RevokeSecurityGroupIngress
                Resource: "*"
              - Effect: Allow
                Action:
                  - ec2:CreateSecurityGroup
                Resource: "*"
              - Effect: Allow
                Action:
                  - ec2:CreateTags
                Resource: arn:aws:ec2:*:*:security-group/*
                Condition:
                  StringEquals:
                    ec2:CreateAction: CreateSecurityGroup
              - Effect: Allow
                Action:
                  - ec2:CreateTags
                  - ec2:DeleteTags
                Resource: arn:aws:ec2:*:*:security-group/*
              - Effect: Allow
                Action:
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:RevokeSecurityGroupIngress
                  - ec2:DeleteSecurityGroup
                Resource: arn:aws:ec2:*:*:security-group/*
              - Effect: Allow
                Action:
                  - elasticloadbalancing:CreateLoadBalancer
                  - elasticloadbalancing:CreateTargetGroup
                Resource: "*"
              - Effect: Allow
                Action:
                  - elasticloadbalancing:CreateListener
                  - elasticloadbalancing:DeleteListener
                  - elasticloadbalancing:CreateRule
                  - elasticloadbalancing:DeleteRule
                Resource: "*"
              - Effect: Allow
                Action:
                  - elasticloadbalancing:AddTags
                  - elasticloadbalancing:RemoveTags
                Resource:
                  - arn:aws:elasticloadbalancing:*:*:loadbalancer/net/*/*
                  - arn:aws:elasticloadbalancing:*:*:loadbalancer/app/*/*
                  - arn:aws:elasticloadbalancing:*:*:targetgroup/*/*
                  - arn:aws:elasticloadbalancing:*:*:listener/net/*/*/*
                  - arn:aws:elasticloadbalancing:*:*:listener/app/*/*/*
                  - arn:aws:elasticloadbalancing:*:*:listener-rule/net/*/*/*/*
                  - arn:aws:elasticloadbalancing:*:*:listener-rule/app/*/*/*/*
              - Effect: Allow
                Action:
                  - elasticloadbalancing:ModifyLoadBalancerAttributes
                  - elasticloadbalancing:SetIpAddressType
                  - elasticloadbalancing:SetSecurityGroups
                  - elasticloadbalancing:SetSubnets
                  - elasticloadbalancing:DeleteLoadBalancer
                  - elasticloadbalancing:ModifyTargetGroup
                  - elasticloadbalancing:ModifyTargetGroupAttributes
                  - elasticloadbalancing:DeleteTargetGroup
                Resource: "*"
              - Effect: Allow
                Action:
                  - elasticloadbalancing:RegisterTargets
                  - elasticloadbalancing:DeregisterTargets
                Resource: arn:aws:elasticloadbalancing:*:*:targetgroup/*/*
              - Effect: Allow
                Action:
                  - elasticloadbalancing:SetWebAcl
                  - elasticloadbalancing:ModifyListener
                  - elasticloadbalancing:AddListenerCertificates
                  - elasticloadbalancing:RemoveListenerCertificates
                  - elasticloadbalancing:ModifyRule
                Resource: "*"

Outputs:
  ClusterName:
    Description: Name of EKS Cluster
    Value: !Ref EKSCluster
  ALBControllerRoleArn:
    Description: ARN of the IAM Role for ALB Controller
    Value: !GetAtt ALBControllerRole.Arn
