AWSTemplateFormatVersion: 2010-09-09
Description: This template creates an EKS cluster with Fargate profiles and AWS Load Balancer Controller support.

Parameters:
  EKSClusterName:
    Description: Name of the EKS Cluster
    Type: String
    Default: aws-deployments-eks-fargate

  EKSClusterRoleName:
    Description: Name of the EKS Cluster Role
    Type: String
    Default: EKSClusterRole-aws-eks-fargate

  FargatePodExecutionRoleName:
    Description: Name of the EKS Fargate Pod Execution Role
    Type: String
    Default: FargatePodExecutionRole-aws-eks-fargate

  VPCStackName:
    Description: Name of the VPC CloudFormation stack to import subnet IDs from
    Type: String
    Default: eks-vpc-stack

Resources:
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref EKSClusterRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  FargatePodExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref FargatePodExecutionRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks-fargate-pods.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSFargatePodExecutionRolePolicy

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref EKSClusterName
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds:
          Fn::Split:
            - ","
            - Fn::ImportValue: !Sub "${VPCStackName}-AllSubnets"
        EndpointPublicAccess: true
        EndpointPrivateAccess: true
      Version: "1.33"

  EKSFargateProfileDefault:
    Type: AWS::EKS::FargateProfile
    Properties:
      ClusterName: !Ref EKSCluster
      FargateProfileName: !Sub "${EKSClusterName}-fargate-profile-default"
      PodExecutionRoleArn: !GetAtt FargatePodExecutionRole.Arn
      Subnets:
        Fn::Split:
          - ","
          - Fn::ImportValue: !Sub "${VPCStackName}-PrivateSubnets"
      Selectors:
        - Namespace: default

  EKSFargateProfileKubeSystem:
    Type: AWS::EKS::FargateProfile
    DependsOn:
      - EKSFargateProfileDefault
    Properties:
      ClusterName: !Ref EKSCluster
      FargateProfileName: !Sub "${EKSClusterName}-fargate-profile-kubesystem"
      PodExecutionRoleArn: !GetAtt FargatePodExecutionRole.Arn
      Subnets:
        Fn::Split:
          - ","
          - Fn::ImportValue: !Sub "${VPCStackName}-PrivateSubnets"
      Selectors:
        - Namespace: kube-system


Outputs:
  ClusterName:
    Description: Name of EKS Cluster
    Value: !Ref EKSCluster
