AWSTemplateFormatVersion: "2010-09-09"
Description: Create ECS Cluster, Task Definition and Fargate Service to run container from ECR

Parameters:
  ECSClusterName:
    Description: Name of the ECS Cluster
    Type: String
    Default: aws-deployment-experiments-cluster

  ECSTaskExecutionRoleName:
    Description: Name of the ECS Task Execution Role
    Type: String
    Default: ECSTaskExecutionRole-aws-experiments

  ECSTaskDefinitionName:
    Description: Name of the ECS Task Definition
    Type: String
    Default: aws-deployment-experiments-task

  ECRImageRepoName:
    Description: Name of the ECR Image Repository
    Type: String
    Default: aws-deployment-experiments-backend

  ECSServiceName:
    Description: Name of the ECS Service
    Type: String
    Default: aws-deployment-experiments-service

  ALBName:
    Description: Name of the Application Load Balancer
    Type: String
    Default: aws-experiments-m2

  TaskVPCID:
    Description: VPC ID where the ECS tasks will run
    Type: String
    Default: vpc-0b28acb0cb7c676f9

  TaskVPCSubnets:
    Description: Comma-separated list of VPC Subnet IDs for the ECS tasks
    Type: CommaDelimitedList
    Default: subnet-0ef08e10d6000f307,subnet-0a960f1032e9dc58e,subnet-0009006416de50ea2

  TaskSecurityGroup:
    Description: Security Group ID for the ECS tasks
    Type: String
    Default: sg-0cba23d8bf0e1d3ef
    MinLength: 1

  WebsiteOriginIDName:
    Description: CloudFront Origin ID for S3 Bucket
    Type: String
    Default: S3Origin

Resources:
  # ---------------------------------------------------------------------------
  # ECS CLUSTER
  # ---------------------------------------------------------------------------
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ECSClusterName
      Tags:
        - Key: Name
          Value: !Ref ECSClusterName

  # ---------------------------------------------------------------------------
  # TASK DEFINITION EXECUTION ROLE
  # ---------------------------------------------------------------------------
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Retain
    Properties:
      RoleName: !Ref ECSTaskExecutionRoleName
      Description: Role for ECS tasks to pull images and write logs
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - "sts:AssumeRole"

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

      Policies:
        - PolicyName: AllowLogGroupCreate
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource: "*"

  # ---------------------------------------------------------------------------
  # ECS TASK DEFINITION
  # ---------------------------------------------------------------------------
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref ECSTaskDefinitionName
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      NetworkMode: awsvpc
      Memory: 512
      Cpu: 256
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: !Ref ECSTaskDefinitionName
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRImageRepoName}:latest"
          Essential: true
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp
              HostPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref "AWS::Region"
              awslogs-group: /ecs/
              awslogs-stream-prefix: ecs
              awslogs-create-group: true

  # --------------------------------------------------------------------------
  # ELASTIC LOAD BALANCER - TARGET GROUP
  # ---------------------------------------------------------------------------
  LoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /api/health
      HealthCheckPort: "80"
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Name: !Sub "${ALBName}-tg-m2"
      VpcId: !Ref TaskVPCID
      TargetType: ip
      IpAddressType: ipv4
      ProtocolVersion: HTTP1
      Protocol: HTTP
      Port: 80

  # --------------------------------------------------------------------------
  # ELASTIC LOAD BALANCER - ALB
  # ---------------------------------------------------------------------------
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: !Sub "${ALBName}-alb-m2"
      Scheme: internet-facing
      SecurityGroups:
        - !Ref TaskSecurityGroup
      Subnets: !Ref TaskVPCSubnets
      Type: application

  # ---------------------------------------------------------------------------
  # ELASTIC LOAD BALANCER - LISTENER
  # ---------------------------------------------------------------------------
  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - ApplicationLoadBalancer
      - LoadBalancerTargetGroup
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref LoadBalancerTargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

  # ---------------------------------------------------------------------------
  # ECS SERVICE
  # ---------------------------------------------------------------------------
  ECSService:
    Type: AWS::ECS::Service
    DependsOn: LoadBalancerListener
    Properties:
      AvailabilityZoneRebalancing: DISABLED
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: !Ref ECSTaskDefinitionName
          ContainerPort: 80
          TargetGroupArn: !Ref LoadBalancerTargetGroup

      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref TaskSecurityGroup
          Subnets: !Ref TaskVPCSubnets

      ServiceName: !Ref ECSServiceName
      TaskDefinition: !Ref ECSTaskDefinition
      Tags:
        - Key: Name
          Value: !Ref ECSServiceName

  # ---------------------------------------------------------------------------
  # CLOUDFRONT CDN
  # ---------------------------------------------------------------------------
  M2CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: ApplicationLoadBalancer
    Properties:
      DistributionConfig:
        Enabled: true
        ConnectionMode: direct
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
          TargetOriginId: !Ref WebsiteOriginIDName
          ViewerProtocolPolicy: redirect-to-https

        CacheBehaviors:
          - PathPattern: /api/*
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # CachingDisabled
            TargetOriginId: ALBOrigin
            ViewerProtocolPolicy: allow-all

        Origins:
          # S3
          - DomainName: !ImportValue S3BucketDomainName
            Id: !Ref WebsiteOriginIDName
            S3OriginConfig: {}
            OriginAccessControlId: !ImportValue M1S3OACPolicy

          # ALB
          - DomainName: !GetAtt ApplicationLoadBalancer.DNSName
            Id: ALBOrigin
            CustomOriginConfig:
              HTTPPort: 80
              OriginProtocolPolicy: http-only
              OriginSSLProtocols:
                - TLSv1.2
      Tags:
        - Key: Name
          Value: aws-deployment-experiments-cdn-m2
        - Key: Description
          Value: Method 2 CDN

  StaticWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: M2CloudfrontDistribution
    DeletionPolicy: Retain
    Properties:
      Bucket: !ImportValue S3BucketName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub
              - "${BucketArn}/*"
              - { BucketArn: !ImportValue S3BucketArn }
            Condition:
              StringEquals:
                "AWS:SourceArn":
                  - !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${M2CloudfrontDistribution}"
                  - !Sub
                    - "arn:aws:cloudfront::${AWS::AccountId}:distribution/${M1Distribution}"
                    - {
                        M1Distribution: !ImportValue M1CloudfrontDistributionID,
                      }
