AWSTemplateFormatVersion: "2010-09-09"
Description: Create S3 Bucket and CloudFront Distribution for Static Website Hosting

Parameters:
  S3BucketName:
    Description: S3 Bucket Name
    Type: String
    Default: aws-deployment-experiments-frontend

  WebsiteOriginIDName:
    Description: CloudFront Origin ID for S3 Bucket
    Type: String
    Default: S3Origin

Resources:
  StaticWebsiteS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      Tags:
        - Key: Context
          Value: aws-deployment-experiments

  S3OACPolicy:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: S3OACPolicy
        Description: Origin Access Control for S3 Bucket
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudfrontCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        ConnectionMode: direct
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
          TargetOriginId: !Ref WebsiteOriginIDName
          ViewerProtocolPolicy: redirect-to-https

        Origins:
          - DomainName: !GetAtt StaticWebsiteS3Bucket.RegionalDomainName
            Id: !Ref WebsiteOriginIDName
            S3OriginConfig: {}
            OriginAccessControlId: !Sub ${S3OACPolicy}
        DefaultRootObject: index.html

      Tags:
        - Key: Name
          Value: aws-deployment-experiments-cdn

  StaticWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticWebsiteS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${StaticWebsiteS3Bucket.Arn}/*"
            Condition:
              StringEquals:
                "AWS:SourceArn": !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudfrontCDN}"
